package com.mycompany.employeesapplication;

import java.util.ArrayList;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author emre2
 */
public class RemoveEmploye extends javax.swing.JFrame {
   
    
    public static int selectedRow;
    DbHelper helper = new DbHelper();
    Connection conn;
    DefaultTableModel model;
public void tabloyuDoldur(){
    model = (DefaultTableModel) tblEmployeeApplication.getModel();
        try {
            ArrayList<Personel> personeller = getEmployees();
            for (Personel personel : personeller) {
                Object[] row = {
                    personel.id,
                    personel.name,
                    personel.surName,
                    personel.getTcNo(),
                    personel.phoneNumber,
                    personel.getAdress(),
                    personel.getSalary(),
                    personel.totalDayOff};
                model.addRow(row);
            }

        } catch (SQLException ex) {
            lblWarn.setText(ex.getMessage());
        }
}
    public RemoveEmploye() {
        initComponents();
        tabloyuDoldur();
    }

    public ArrayList<Personel> getEmployees() throws SQLException {
        Connection conn = null;
        DbHelper helper = new DbHelper();
        Statement statement = null;
        ResultSet resultSet;
        ArrayList<Personel> personeller = null;
        try {
            conn = helper.getConnection();
            statement = conn.createStatement();
            resultSet = statement.executeQuery("SELECT * from employee");
            personeller = new ArrayList<Personel>();
            while (resultSet.next()) {
                personeller.add(new Personel(resultSet.getInt("id"), resultSet.getString("name"),
                        resultSet.getString("surName"),
                        resultSet.getString("phoneNumber"),
                        resultSet.getString("tcNo"),
                        resultSet.getString("adress"),
                        resultSet.getDouble("salary"),
                        resultSet.getInt("totaldayOff")));
            }
        } catch (Exception e) {
            lblWarn.setText(e.getMessage());
        } finally {
            statement.close();
            conn.close();
        }
        return personeller;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSerach = new javax.swing.JTextField();
        lblEmployeeName = new javax.swing.JLabel();
        btnRemove = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployeeApplication = new javax.swing.JTable();
        lblWarn = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtSerach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerachActionPerformed(evt);
            }
        });
        txtSerach.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSerachKeyReleased(evt);
            }
        });

        lblEmployeeName.setText("Employee Name:");

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        tblEmployeeApplication.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "SurName", "TcNo", "PhoneNumber", "Adress", "Salary", "DayOff"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEmployeeApplication);

        jScrollPane2.setViewportView(jScrollPane1);

        btnBack.setText("←");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(lblEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtSerach, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRemove)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWarn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSerach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmployeeName)
                    .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWarn)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSerachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerachActionPerformed

    private void txtSerachKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSerachKeyReleased
        String searchKey = txtSerach.getText();
        TableRowSorter<DefaultTableModel> tableRowSorter
                = new TableRowSorter<DefaultTableModel>(model);
        tblEmployeeApplication.setRowSorter(tableRowSorter);
        tableRowSorter.setRowFilter(RowFilter.regexFilter(searchKey));
    }//GEN-LAST:event_txtSerachKeyReleased
    
    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // Seçili satırın ID'sini alalım
        selectedRow = tblEmployeeApplication.getSelectedRow();
        // Seçili satırın verisini alalım (örneğin, ilk sütundaki veriyi alalım)
        int column = 0; // İlgili sütunun indeksi
        int value = (int) tblEmployeeApplication.getModel().getValueAt(selectedRow, column);
        // Kullanıcıya bir uyarı mesajı gösterelim
        String[] options = {"Yes, Remove", "NO, Cancel"};
        int dialogResult = JOptionPane.showOptionDialog(null, "Are you sure?", "WARNİNG", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[1]);

        // Kullanıcının seçimine göre işlem yapalım
        if (dialogResult == JOptionPane.YES_OPTION) {
            // Eğer "Evet" seçeneği seçilmişse, veriyi silme işlemini burada gerçekleştirin
            String deleteSql = "DELETE FROM employee WHERE id = ?; ";
            conn = helper.getConnection();
            try {
                PreparedStatement preparedStatement = conn.prepareStatement(deleteSql);
                preparedStatement.setInt(1, value);
                int affectedRows = preparedStatement.executeUpdate();
            } catch (SQLException e) {
                e.printStackTrace();
            }finally{
                try {
                    conn.close();
                } catch (SQLException ex) {
                   ex.printStackTrace();
                }
                tabloyuDoldur();
            }
// Burada tablodan veriyi kaldırma işlemini yapabilirsiniz.

        } else if (dialogResult == JOptionPane.NO_OPTION) {
            /// Eğer "Hayır" seçeneği seçilmişse, diyalog penceresini kapatın
            JOptionPane.getRootFrame().dispose();
        } else {
            // Kullanıcı pencereyi kapatırsa da işlemi iptal edin
            JOptionPane.getRootFrame().dispose();
        }

    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
         RemoveEmploye removeEmploye = new RemoveEmploye();
        removeEmploye.dispose();
        FrameOfAdministrator frameOfAdministrator = new FrameOfAdministrator();
        frameOfAdministrator.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoveEmploye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoveEmploye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoveEmploye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoveEmploye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoveEmploye().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRemove;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblEmployeeName;
    private javax.swing.JLabel lblWarn;
    private javax.swing.JTable tblEmployeeApplication;
    private javax.swing.JTextField txtSerach;
    // End of variables declaration//GEN-END:variables

}
