package com.mycompany.employeesapplication;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author emre2
 */
public class SearchEmployee extends javax.swing.JFrame {

    public static int selectedRow;
    DbHelper helper = new DbHelper();
    Connection conn;
    DefaultTableModel model;

    /**
     * Creates new form SearchEmployee
     */
    public SearchEmployee() {
        initComponents();
        model = (DefaultTableModel) tblEmployeeApplication.getModel();
        try {
            ArrayList<Personel> personeller = getEmployees();
            for (Personel personel : personeller) {
                Object[] row = {
                    personel.id,
                    personel.name,
                    personel.surName,
                    personel.getTcNo(),
                    personel.phoneNumber,
                    personel.getAdress(),
                    personel.getSalary(),
                    personel.totalDayOff};
                model.addRow(row);
           for (int i = 0; i < row.length; i++) {
                System.out.println(row[i]);
            }
            }
            

        } catch (SQLException ex) {
            lblWarn.setText(ex.getMessage());
        }
    }

    public ArrayList<Personel> getEmployees() throws SQLException {
        
        
        Statement statement = null;
        ResultSet resultSet;
        ArrayList<Personel> personeller = new ArrayList<Personel>();
        try {
            conn = helper.getConnection();
                                        System.out.println("baglantı oldu");

            statement = conn.createStatement();
            resultSet = statement.executeQuery("SELECT * from employee");
            
            personeller = new ArrayList<Personel>();
                            System.out.println("personeler aray olusturuldı");

            while (resultSet.next()) {
                System.out.println("while girildi");
                personeller.add(new Personel(
                        resultSet.getInt("id"), 
                        resultSet.getString("name"),
                        resultSet.getString("surName"),
                        resultSet.getString("phoneNumber"),
                        resultSet.getString("tcNo"),
                        resultSet.getString("adress"),
                        resultSet.getDouble("salary"),
                        resultSet.getInt("totaldayOff")));
                                System.out.println("whiledan cıkıldı");

            }
        } catch (Exception e) {
            lblWarn.setText(e.getMessage());
        } finally {
            statement.close();
            conn.close();
        }
        return personeller;

    }
public void PrintEmployees() {
    try {
        ArrayList<Personel> personeller = getEmployees();
        for (Personel personel : personeller) {
            System.out.println(personel);
        }
    } catch (SQLException ex) {
        System.out.println("Veritabanından personel bilgileri alınırken bir hata oluştu: " + ex.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSerach = new javax.swing.JTextField();
        lblEmployeeName = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployeeApplication = new javax.swing.JTable();
        lblWarn = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtSerach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerachActionPerformed(evt);
            }
        });
        txtSerach.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSerachKeyReleased(evt);
            }
        });

        lblEmployeeName.setText("Employee Name:");

        btnSearch.setIcon(new javax.swing.ImageIcon("C:\\Users\\emre2\\Pictures\\search_4337-fit-35x35.png")); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tblEmployeeApplication.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "SurName", "TcNo", "PhoneNumber", "Adress", "Salary", "DayOff"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEmployeeApplication);

        jScrollPane2.setViewportView(jScrollPane1);

        btnBack.setText("←");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lblEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSerach, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearch)
                        .addGap(95, 95, 95)
                        .addComponent(lblWarn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSerach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblEmployeeName)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBack))
                    .addComponent(lblWarn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSerachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerachActionPerformed

    private void txtSerachKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSerachKeyReleased
        String searchKey = txtSerach.getText();
        TableRowSorter<DefaultTableModel> tableRowSorter
                = new TableRowSorter<DefaultTableModel>(model);
        tblEmployeeApplication.setRowSorter(tableRowSorter);
        tableRowSorter.setRowFilter(RowFilter.regexFilter(searchKey));
    }//GEN-LAST:event_txtSerachKeyReleased

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

        conn = helper.getConnection();
        String searchSql = "SELECT * FROM employee WHERE name LIKE ?";
        try (PreparedStatement preparedStatement = conn.prepareStatement(searchSql)) {
            preparedStatement.setString(1, "%" + txtSerach.getText() + "%");
            // Diğer işlemleri burada gerçekleştirin...
            
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
      this.setVisible(false);
        FrameOfAdministrator frameOfAdministrator = new FrameOfAdministrator();
        frameOfAdministrator.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblEmployeeName;
    private javax.swing.JLabel lblWarn;
    private javax.swing.JTable tblEmployeeApplication;
    private javax.swing.JTextField txtSerach;
    // End of variables declaration//GEN-END:variables
}
