package com.mycompany.employeesapplication;

import java.sql.*;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class UpdateInfromation extends javax.swing.JFrame {

    DbHelper helper = new DbHelper();
    Connection conn = helper.getConnection();
    FrameOfEmployee frameOfEmployee = new FrameOfEmployee();

    public UpdateInfromation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        txtUserName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtAdress = new javax.swing.JTextField();
        btnUserNameSave = new javax.swing.JButton();
        btnPasswordSave = new javax.swing.JButton();
        btnPhoneSave = new javax.swing.JButton();
        btnAdressSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        paswordCheck = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        lblPasswordAgain = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtUserName.setText("User Name");
        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });

        txtPhone.setText("Phone");

        txtAdress.setText("Adress");

        btnUserNameSave.setText("Save");
        btnUserNameSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserNameSaveActionPerformed(evt);
            }
        });

        btnPasswordSave.setText("Save");
        btnPasswordSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasswordSaveActionPerformed(evt);
            }
        });

        btnPhoneSave.setText("Save");
        btnPhoneSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhoneSaveActionPerformed(evt);
            }
        });

        btnAdressSave.setText("Save");
        btnAdressSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdressSaveActionPerformed(evt);
            }
        });

        btnBack.setText("←");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        password.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                passwordComponentHidden(evt);
            }
        });

        jLabel1.setText("Password");

        lblPasswordAgain.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblPasswordAgain.setText("enter the password again");

        lblUserName.setText("userName");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(txtAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdressSave))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(txtPhone)
                        .addGap(18, 18, 18)
                        .addComponent(btnPhoneSave))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtUserName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(password, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paswordCheck, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUserNameSave)
                            .addComponent(btnPasswordSave)))
                    .addComponent(lblPasswordAgain, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(124, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUserName)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblUserName)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUserNameSave))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paswordCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPasswordSave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPasswordAgain)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPhoneSave))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdressSave))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserNameSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserNameSaveActionPerformed

        String updateSql = "UPDATE logofemploye SET username = ? WHERE name = ?";
        try (PreparedStatement preparedStatement = conn.prepareStatement(updateSql)) {
            preparedStatement.setString(1, txtUserName.getText()); // UserName
            preparedStatement.setString(2, lblUserName.getText()); // Condition
            int rowsAffected = preparedStatement.executeUpdate();

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnUserNameSaveActionPerformed

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void passwordComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_passwordComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordComponentHidden

    private void btnPasswordSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasswordSaveActionPerformed
        String updateSql = "UPDATE logofemploye SET password = ? WHERE name = ?";
        if (password.getPassword() == paswordCheck.getPassword()) {
            try (PreparedStatement preparedStatement = conn.prepareStatement(updateSql)) {
                String UpdatePassword = new String(password.getPassword());
                if (PasswordUtils.isValidPassword(UpdatePassword)) {
                    preparedStatement.setString(1, PasswordUtils.hashPassword(UpdatePassword)); // Şifre hash'lenmiş hali 
                } else {
                    lblPasswordAgain.setText("The password must be at least 8 digits and contain one uppercase letter.");
                }
                preparedStatement.setString(2, lblUserName.getText()); // Condition
                int rowsAffected = preparedStatement.executeUpdate();

            } catch (SQLException e) {
                e.printStackTrace();
            }

        } else {
            lblPasswordAgain.setText("THE PASSWORDS ARE NOT THE SAME");
        }


    }//GEN-LAST:event_btnPasswordSaveActionPerformed

    private void btnPhoneSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhoneSaveActionPerformed
    String updateSql = "UPDATE employee SET phoneNumber = ? WHERE name = ?";
    try (PreparedStatement preparedStatement = conn.prepareStatement(updateSql)) {
        preparedStatement.setString(1, txtPhone.getText()); // Phone
        preparedStatement.setString(2, lblUserName.getText()); // Condition
        int rowsAffected = preparedStatement.executeUpdate();
        
        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(this, "Telefon numarası başarıyla güncellendi.");
        } else {
            JOptionPane.showMessageDialog(this, "Telefon numarası güncellenirken bir hata oluştu.");
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Veritabanına erişim sırasında bir hata oluştu: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnPhoneSaveActionPerformed

    private void btnAdressSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdressSaveActionPerformed
        String updateSql = "UPDATE employee SET adress = ? WHERE name = ?";
        try (PreparedStatement preparedStatement = conn.prepareStatement(updateSql)) {
            preparedStatement.setString(1, txtAdress.getText()); // UserName
            preparedStatement.setString(2, lblUserName.getText()); // Condition
            int rowsAffected = preparedStatement.executeUpdate();

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAdressSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.setVisible(false);
        frameOfEmployee.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateInfromation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateInfromation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateInfromation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateInfromation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateInfromation().setVisible(true);
            }
        });
    }

    public void setUserNameLabelText(String text) {
        lblUserName.setText(text);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdressSave;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPasswordSave;
    private javax.swing.JButton btnPhoneSave;
    private javax.swing.JButton btnUserNameSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblPasswordAgain;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPasswordField password;
    private javax.swing.JPasswordField paswordCheck;
    private javax.swing.JTextField txtAdress;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
